# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 761)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(253, 253, 253);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 281, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.verticalLayoutWidget)
        self.treeWidget.setStyleSheet("font: 20pt \"黑体\";\n"
"border:1px solid rgb(74, 147, 221);\n"
"color: rgb(50, 50, 50);\n"
"\n"
"")
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 951, 91))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("font: 24pt \"黑体\";\n"
"background-color: rgb(220, 242, 255);\n"
"border:1px solid rgb(74, 147, 221)")
        self.label_6.setObjectName("label_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 951, 661))
        self.frame.setStyleSheet("#frame{border:1px solid rgb(74, 147, 221)}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 620, 951, 41))
        self.label.setStyleSheet("background-color: rgb(220, 242, 255);\n"
"font: 12pt \"Times New Roman\";\n"
"border:1px solid rgb(74, 147, 221);\n"
"color: rgb(15, 108, 189);\n"
"\n"
"")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(290, 100, 641, 511))
        self.stackedWidget.setStyleSheet("#page1{border:1px solid rgb(74, 147, 221)}\n"
"#page2{border:1px solid rgb(74, 147, 221)}\n"
"#page3{border:1px solid rgb(74, 147, 221)}\n"
"#page4{border:1px solid rgb(74, 147, 221)}\n"
"#page5{border:1px solid rgb(74, 147, 221)}\n"
"#page6{border:1px solid rgb(74, 147, 221)}\n"
"#page7{border:1px solid rgb(74, 147, 221)}\n"
"#page8{border:1px solid rgb(74, 147, 221)}\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.label_4 = QtWidgets.QLabel(self.page1)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 641, 41))
        self.label_4.setStyleSheet("font: 16pt \"黑体\";\n"
"background-color: rgb(239, 246, 255);\n"
"border:1px solid rgb(74, 147, 221)\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.page1)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 41, 41))
        self.label_2.setStyleSheet("color: rgb(47, 47, 47);\n"
"font: 14pt \"Arial\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page1)
        self.label_3.setGeometry(QtCore.QRect(140, 140, 41, 41))
        self.label_3.setStyleSheet("color: rgb(47, 47, 47);\n"
"font: 14pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.page1)
        self.label_5.setGeometry(QtCore.QRect(140, 200, 41, 41))
        self.label_5.setStyleSheet("font: 75 14pt \"Arial\";\n"
"color: rgb(47, 47, 47);")
        self.label_5.setObjectName("label_5")
        self.comboBox_SC = QtWidgets.QComboBox(self.page1)
        self.comboBox_SC.setGeometry(QtCore.QRect(210, 210, 211, 31))
        self.comboBox_SC.setStyleSheet("font: 12pt \"黑体\";\n"
"color: rgb(47, 47, 47);\n"
"border:1px solid rgb(156, 156, 156)")
        self.comboBox_SC.setObjectName("comboBox_SC")
        self.comboBox_SC.addItem("")
        self.comboBox_SC.addItem("")
        self.textBrowser_state = QtWidgets.QTextBrowser(self.page1)
        self.textBrowser_state.setGeometry(QtCore.QRect(290, 340, 131, 31))
        self.textBrowser_state.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textBrowser_state.setObjectName("textBrowser_state")
        self.pushButton_close = QtWidgets.QPushButton(self.page1)
        self.pushButton_close.setGeometry(QtCore.QRect(120, 340, 61, 31))
        self.pushButton_close.setStyleSheet("font: 12pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_cnn = QtWidgets.QPushButton(self.page1)
        self.pushButton_cnn.setGeometry(QtCore.QRect(180, 340, 61, 31))
        self.pushButton_cnn.setStyleSheet("font: 12pt \"黑体\";\n"
"\n"
"")
        self.pushButton_cnn.setObjectName("pushButton_cnn")
        self.textEdit_ip = QtWidgets.QTextEdit(self.page1)
        self.textEdit_ip.setGeometry(QtCore.QRect(210, 90, 211, 31))
        self.textEdit_ip.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textEdit_ip.setObjectName("textEdit_ip")
        self.textEdit_port = QtWidgets.QTextEdit(self.page1)
        self.textEdit_port.setGeometry(QtCore.QRect(210, 150, 211, 31))
        self.textEdit_port.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textEdit_port.setObjectName("textEdit_port")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page2.setObjectName("page2")
        self.label_7 = QtWidgets.QLabel(self.page2)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 641, 41))
        self.label_7.setStyleSheet("font: 16pt \"黑体\";\n"
"background-color: rgb(239, 246, 255);\n"
"border:1px solid rgb(74, 147, 221)\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page2)
        self.label_8.setGeometry(QtCore.QRect(103, 75, 71, 21))
        self.label_8.setStyleSheet("font: 12pt \"黑体\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page2)
        self.label_9.setGeometry(QtCore.QRect(97, 145, 81, 21))
        self.label_9.setStyleSheet("font: 12pt \"黑体\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page2)
        self.label_10.setGeometry(QtCore.QRect(98, 214, 81, 21))
        self.label_10.setStyleSheet("font: 12pt \"黑体\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page2)
        self.label_11.setGeometry(QtCore.QRect(97, 275, 91, 21))
        self.label_11.setStyleSheet("font: 12pt \"黑体\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page2)
        self.label_12.setGeometry(QtCore.QRect(100, 335, 81, 61))
        self.label_12.setStyleSheet("font: 12pt \"黑体\";")
        self.label_12.setObjectName("label_12")
        self.pushButton_2apply = QtWidgets.QPushButton(self.page2)
        self.pushButton_2apply.setGeometry(QtCore.QRect(290, 440, 101, 31))
        self.pushButton_2apply.setStyleSheet("font: 12pt \"黑体\";")
        self.pushButton_2apply.setObjectName("pushButton_2apply")
        self.textEdit_id = QtWidgets.QTextEdit(self.page2)
        self.textEdit_id.setGeometry(QtCore.QRect(190, 70, 321, 31))
        self.textEdit_id.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textEdit_id.setObjectName("textEdit_id")
        self.textEdit_project = QtWidgets.QTextEdit(self.page2)
        self.textEdit_project.setGeometry(QtCore.QRect(190, 140, 321, 31))
        self.textEdit_project.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textEdit_project.setObjectName("textEdit_project")
        self.textEdit_location1 = QtWidgets.QTextEdit(self.page2)
        self.textEdit_location1.setGeometry(QtCore.QRect(190, 210, 91, 31))
        self.textEdit_location1.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textEdit_location1.setObjectName("textEdit_location1")
        self.textEdit_location2 = QtWidgets.QTextEdit(self.page2)
        self.textEdit_location2.setGeometry(QtCore.QRect(290, 210, 221, 31))
        self.textEdit_location2.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textEdit_location2.setObjectName("textEdit_location2")
        self.dateEdit = QtWidgets.QDateEdit(self.page2)
        self.dateEdit.setGeometry(QtCore.QRect(190, 270, 321, 31))
        self.dateEdit.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.dateEdit.setObjectName("dateEdit")
        self.textEdit_remark = QtWidgets.QTextEdit(self.page2)
        self.textEdit_remark.setGeometry(QtCore.QRect(190, 330, 321, 71))
        self.textEdit_remark.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textEdit_remark.setObjectName("textEdit_remark")
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.label_13 = QtWidgets.QLabel(self.page3)
        self.label_13.setGeometry(QtCore.QRect(81, 85, 101, 41))
        self.label_13.setStyleSheet("background-color: rgb(220, 242, 255);\n"
"font: 12pt \"黑体\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page3)
        self.label_14.setGeometry(QtCore.QRect(81, 205, 101, 41))
        self.label_14.setStyleSheet("background-color: rgb(220, 242, 255);\n"
"font: 12pt \"黑体\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page3)
        self.label_15.setGeometry(QtCore.QRect(80, 330, 101, 41))
        self.label_15.setStyleSheet("background-color: rgb(220, 242, 255);\n"
"font: 12pt \"黑体\";")
        self.label_15.setObjectName("label_15")
        self.pushButton_fclose = QtWidgets.QPushButton(self.page3)
        self.pushButton_fclose.setGeometry(QtCore.QRect(404, 90, 61, 31))
        self.pushButton_fclose.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_fclose.setObjectName("pushButton_fclose")
        self.pushButton_fopen = QtWidgets.QPushButton(self.page3)
        self.pushButton_fopen.setGeometry(QtCore.QRect(471, 90, 61, 31))
        self.pushButton_fopen.setStyleSheet("font: 10pt \"黑体\";")
        self.pushButton_fopen.setObjectName("pushButton_fopen")
        self.pushButton_sopen = QtWidgets.QPushButton(self.page3)
        self.pushButton_sopen.setGeometry(QtCore.QRect(470, 210, 61, 31))
        self.pushButton_sopen.setStyleSheet("font: 10pt \"黑体\";")
        self.pushButton_sopen.setObjectName("pushButton_sopen")
        self.pushButton_sclose = QtWidgets.QPushButton(self.page3)
        self.pushButton_sclose.setGeometry(QtCore.QRect(403, 210, 61, 31))
        self.pushButton_sclose.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_sclose.setObjectName("pushButton_sclose")
        self.pushButton_copen = QtWidgets.QPushButton(self.page3)
        self.pushButton_copen.setGeometry(QtCore.QRect(470, 340, 61, 31))
        self.pushButton_copen.setStyleSheet("font: 10pt \"黑体\";")
        self.pushButton_copen.setObjectName("pushButton_copen")
        self.pushButton_cclose = QtWidgets.QPushButton(self.page3)
        self.pushButton_cclose.setGeometry(QtCore.QRect(403, 340, 61, 31))
        self.pushButton_cclose.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_cclose.setObjectName("pushButton_cclose")
        self.label_16 = QtWidgets.QLabel(self.page3)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 641, 41))
        self.label_16.setStyleSheet("font: 16pt \"黑体\";\n"
"background-color: rgb(239, 246, 255);\n"
"border:1px solid rgb(74, 147, 221)\n"
"\n"
"")
        self.label_16.setObjectName("label_16")
        self.textBrowser_fetch = QtWidgets.QTextBrowser(self.page3)
        self.textBrowser_fetch.setGeometry(QtCore.QRect(210, 90, 161, 31))
        self.textBrowser_fetch.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textBrowser_fetch.setObjectName("textBrowser_fetch")
        self.textBrowser_save = QtWidgets.QTextBrowser(self.page3)
        self.textBrowser_save.setGeometry(QtCore.QRect(210, 210, 161, 31))
        self.textBrowser_save.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textBrowser_save.setObjectName("textBrowser_save")
        self.textBrowser_control = QtWidgets.QTextBrowser(self.page3)
        self.textBrowser_control.setGeometry(QtCore.QRect(210, 340, 161, 31))
        self.textBrowser_control.setStyleSheet("font: 12pt \"黑体\";\n"
"border:1px solid rgb(156, 156, 156)")
        self.textBrowser_control.setObjectName("textBrowser_control")
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.tableWidget_page4 = QtWidgets.QTableWidget(self.page4)
        self.tableWidget_page4.setGeometry(QtCore.QRect(10, 50, 621, 391))
        self.tableWidget_page4.setStyleSheet("font: 12pt \"黑体\";")
        self.tableWidget_page4.setObjectName("tableWidget_page4")
        self.tableWidget_page4.setColumnCount(6)
        self.tableWidget_page4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget_page4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget_page4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page4.setHorizontalHeaderItem(5, item)
        self.label_31 = QtWidgets.QLabel(self.page4)
        self.label_31.setGeometry(QtCore.QRect(0, 0, 641, 41))
        self.label_31.setStyleSheet("font: 16pt \"黑体\";\n"
"background-color: rgb(239, 246, 255);\n"
"border:1px solid rgb(74, 147, 221)\n"
"\n"
"")
        self.label_31.setObjectName("label_31")
        self.layoutWidget = QtWidgets.QWidget(self.page4)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 450, 421, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4import = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4import.setStyleSheet("font: 10pt \"华文宋体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4import.setObjectName("pushButton_4import")
        self.horizontalLayout.addWidget(self.pushButton_4import)
        self.pushButton_4add = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4add.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4add.setObjectName("pushButton_4add")
        self.horizontalLayout.addWidget(self.pushButton_4add)
        self.pushButton_4edit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4edit.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4edit.setObjectName("pushButton_4edit")
        self.horizontalLayout.addWidget(self.pushButton_4edit)
        self.pushButton_4delet = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4delet.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4delet.setObjectName("pushButton_4delet")
        self.horizontalLayout.addWidget(self.pushButton_4delet)
        self.pushButton_effctive = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_effctive.setStyleSheet("font: 10pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_effctive.setObjectName("pushButton_effctive")
        self.horizontalLayout.addWidget(self.pushButton_effctive)
        self.stackedWidget.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.label_33 = QtWidgets.QLabel(self.page5)
        self.label_33.setGeometry(QtCore.QRect(0, 0, 641, 41))
        self.label_33.setStyleSheet("font: 16pt \"黑体\";\n"
"background-color: rgb(239, 246, 255);\n"
"border:1px solid rgb(74, 147, 221)\n"
"\n"
"")
        self.label_33.setObjectName("label_33")
        self.label_17 = QtWidgets.QLabel(self.page5)
        self.label_17.setGeometry(QtCore.QRect(40, 410, 141, 51))
        self.label_17.setStyleSheet("background-color: rgb(216, 216, 216);\n"
"font: 12pt \"黑体\";")
        self.label_17.setObjectName("label_17")
        self.textEdit_filepath = QtWidgets.QTextEdit(self.page5)
        self.textEdit_filepath.setGeometry(QtCore.QRect(180, 410, 311, 51))
        self.textEdit_filepath.setStyleSheet("font: 10pt \"华文宋体\";")
        self.textEdit_filepath.setObjectName("textEdit_filepath")
        self.layoutWidget1 = QtWidgets.QWidget(self.page5)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 70, 326, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5import = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5import.setStyleSheet("font: 16pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5import.setObjectName("pushButton_5import")
        self.verticalLayout_2.addWidget(self.pushButton_5import)
        self.pushButton_5save = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5save.setStyleSheet("background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"黑体\";")
        self.pushButton_5save.setObjectName("pushButton_5save")
        self.verticalLayout_2.addWidget(self.pushButton_5save)
        self.pushButton_5fetch = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5fetch.setStyleSheet("font: 16pt \"黑体\";\n"
"background-color: rgb(118, 126, 156);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5fetch.setObjectName("pushButton_5fetch")
        self.verticalLayout_2.addWidget(self.pushButton_5fetch)
        self.stackedWidget.addWidget(self.page5)
        self.page6 = QtWidgets.QWidget()
        self.page6.setStyleSheet("background-color: rgb(211, 229, 255);")
        self.page6.setObjectName("page6")
        self.stackedWidget.addWidget(self.page6)
        self.page7 = QtWidgets.QWidget()
        self.page7.setObjectName("page7")
        self.label_picture = QtWidgets.QLabel(self.page7)
        self.label_picture.setGeometry(QtCore.QRect(10, 40, 621, 431))
        self.label_picture.setText("")
        self.label_picture.setObjectName("label_picture")
        self.stackedWidget.addWidget(self.page7)
        self.page8 = QtWidgets.QWidget()
        self.page8.setObjectName("page8")
        self.label_version = QtWidgets.QLabel(self.page8)
        self.label_version.setGeometry(QtCore.QRect(50, 60, 171, 21))
        self.label_version.setStyleSheet("color: rgb(66, 66, 66);\n"
"font: 16pt \"华文宋体\";")
        self.label_version.setObjectName("label_version")
        self.stackedWidget.addWidget(self.page8)
        self.frame.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "#"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "连接iotE"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "iotE"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "基本信息"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "服务状态"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "参数配置"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "设备配置"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "输入设备"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "输出设备"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "电源设备"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "导入/导出"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "功能"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "数据显示"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "输入数据"))
        self.treeWidget.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "输出状态"))
        self.treeWidget.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "电源状态"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "软件设置"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "新建子项目"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "帮助"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "示意图"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "关于"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "               物联网边缘处理终端管理器 iotE-Manger"))
        self.label.setText(_translate("MainWindow", "                                                                                                                  @ dx"))
        self.label_4.setText(_translate("MainWindow", " 连接iot-E"))
        self.label_2.setText(_translate("MainWindow", " IP"))
        self.label_3.setText(_translate("MainWindow", "Port"))
        self.label_5.setText(_translate("MainWindow", "S/C"))
        self.comboBox_SC.setItemText(0, _translate("MainWindow", "服务器"))
        self.comboBox_SC.setItemText(1, _translate("MainWindow", "客户端"))
        self.textBrowser_state.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">未连接</p></body></html>"))
        self.pushButton_close.setText(_translate("MainWindow", "关闭"))
        self.pushButton_cnn.setText(_translate("MainWindow", "连接"))
        self.label_7.setText(_translate("MainWindow", " iotE基本信息"))
        self.label_8.setText(_translate("MainWindow", "编号"))
        self.label_9.setText(_translate("MainWindow", "所属项目"))
        self.label_10.setText(_translate("MainWindow", "部署位置"))
        self.label_11.setText(_translate("MainWindow", "启用日期"))
        self.label_12.setText(_translate("MainWindow", "备注"))
        self.pushButton_2apply.setText(_translate("MainWindow", "应用"))
        self.textEdit_id.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'华文宋体\';\"><br /></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "数据采集服务"))
        self.label_14.setText(_translate("MainWindow", "本地存储服务"))
        self.label_15.setText(_translate("MainWindow", "本地控制服务"))
        self.pushButton_fclose.setText(_translate("MainWindow", "关闭"))
        self.pushButton_fopen.setText(_translate("MainWindow", "启动"))
        self.pushButton_sopen.setText(_translate("MainWindow", "启动"))
        self.pushButton_sclose.setText(_translate("MainWindow", "关闭"))
        self.pushButton_copen.setText(_translate("MainWindow", "启动"))
        self.pushButton_cclose.setText(_translate("MainWindow", "关闭"))
        self.label_16.setText(_translate("MainWindow", " iotE服务状态"))
        self.textBrowser_fetch.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_save.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        item = self.tableWidget_page4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.tableWidget_page4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称*"))
        item = self.tableWidget_page4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "部署位置"))
        item = self.tableWidget_page4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "采集周期"))
        item = self.tableWidget_page4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "启用日期"))
        item = self.tableWidget_page4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "备注"))
        self.label_31.setText(_translate("MainWindow", "输入设备参数配置"))
        self.pushButton_4import.setText(_translate("MainWindow", "导入"))
        self.pushButton_4add.setText(_translate("MainWindow", "新增"))
        self.pushButton_4edit.setText(_translate("MainWindow", "编辑"))
        self.pushButton_4delet.setText(_translate("MainWindow", "删除"))
        self.pushButton_effctive.setText(_translate("MainWindow", "生效"))
        self.label_33.setText(_translate("MainWindow", "导入/导出参数配置"))
        self.label_17.setText(_translate("MainWindow", "本地文件保存位置："))
        self.pushButton_5import.setText(_translate("MainWindow", "导入本地已配置参数"))
        self.pushButton_5save.setText(_translate("MainWindow", "导出到本地"))
        self.pushButton_5fetch.setText(_translate("MainWindow", "获取终端现配置参数"))
        self.label_version.setText(_translate("MainWindow", "软件版本号：v0.76"))
