# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 579)
        self.tableWidget_page6 = QtWidgets.QTableWidget(Form)
        self.tableWidget_page6.setGeometry(QtCore.QRect(20, 100, 621, 421))
        self.tableWidget_page6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"华文宋体\";")
        self.tableWidget_page6.setObjectName("tableWidget_page6")
        self.tableWidget_page6.setColumnCount(6)
        self.tableWidget_page6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_page6.setHorizontalHeaderItem(5, item)
        self.textBrowser_6data = QtWidgets.QTextBrowser(Form)
        self.textBrowser_6data.setGeometry(QtCore.QRect(20, 60, 311, 31))
        self.textBrowser_6data.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"华文宋体\";")
        self.textBrowser_6data.setObjectName("textBrowser_6data")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(10, 10, 641, 41))
        self.label_34.setStyleSheet("font: 20pt \"华文宋体\";\n"
"background-color: rgb(239, 246, 255);\n"
"border:1px solid rgb(74, 147, 221)\n"
"\n"
"")
        self.label_34.setObjectName("label_34")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 641, 551))
        self.widget.setStyleSheet("background-color: rgb(211, 229, 255);\n"
"border:1px solid rgb(74, 147, 221)")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.tableWidget_page6.raise_()
        self.textBrowser_6data.raise_()
        self.label_34.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数据展示"))
        item = self.tableWidget_page6.horizontalHeaderItem(0)
        item.setText(_translate("Form", "设备名"))
        item = self.tableWidget_page6.horizontalHeaderItem(1)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget_page6.horizontalHeaderItem(2)
        item.setText(_translate("Form", "部署位置"))
        item = self.tableWidget_page6.horizontalHeaderItem(3)
        item.setText(_translate("Form", "数值"))
        item = self.tableWidget_page6.horizontalHeaderItem(4)
        item.setText(_translate("Form", "时间"))
        item = self.tableWidget_page6.horizontalHeaderItem(5)
        item.setText(_translate("Form", "数据库"))
        self.label_34.setText(_translate("Form", "传感器数据显示"))
